import { z } from "zod";
import { htmlToText } from "../connector/html.js";
import { inferSeniorityFromTitle } from "../connector/seniority.js";
import type {
  IngestInstruction,
  InstructionSourceConnector,
  NormalizedDiscoveredPosting,
  SourceQuery
} from "../connector/types.js";

/**
 * Schema for the WebFetch callback payload. Claude is expected to
 * fetch the career page (using the `web_fetch` work item) and
 * synthesize a list of postings — strategy varies by page (HTML
 * scraping, JSON-LD, embedded ATS data, JS-rendered content). The
 * prompt to WebFetch is generated by Claude itself based on the page's
 * structure; this connector only normalizes the resulting payload.
 *
 * `company` is optional — we fall back to the URL host when absent
 * (e.g. https://anthropic.com/careers/... → "Anthropic").
 */
const careerPagePostingSchema = z
  .object({
    title: z.string().min(1),
    url: z.string().min(1),
    company: z.string().optional().nullable(),
    description: z.string().optional().nullable(),
    locations: z
      .union([z.string(), z.array(z.string())])
      .optional()
      .nullable(),
    employment_type_hint: z.string().optional().nullable()
  })
  .passthrough();

const careerPagePayloadSchema = z.object({
  postings: z.array(careerPagePostingSchema)
});

export type CareerPageConnectorOptions = {
  /**
   * Optional fallback company name. When provided, used instead of the
   * URL-host derivation when a posting lacks an explicit company.
   * Useful when the saved-search query already names the org.
   */
  defaultCompany?: string;
};

/**
 * career_page connector. Routes through Claude's WebFetch tool because
 * different career pages require different extraction strategies, and
 * Claude can apply intelligence to the fetched content via the prompt
 * parameter. We do not fetch directly — that would require us to
 * pre-compile per-org scrapers.
 */
export function careerPageConnector(
  opts: CareerPageConnectorOptions = {}
): InstructionSourceConnector {
  return {
    kind: "instruction",
    id() {
      return "career_page";
    },
    description() {
      return "Generic career-page connector via Claude WebFetch. Claude fetches the URL, applies a page-specific extraction prompt, and calls back with a list of postings.";
    },
    discoverInstruction(
      query: SourceQuery,
      runId: string
    ): IngestInstruction {
      if (query.source !== "career_page") {
        throw new Error(
          `careerPageConnector: expected query.source === "career_page", got "${query.source}"`
        );
      }
      return {
        kind: "ingest_instruction",
        source: "career_page",
        work_items: [
          {
            kind: "web_fetch",
            url: query.url
          }
        ],
        callback_tool: "record_discovered_postings",
        search_run_id: runId
      };
    },
    recordResults(payload: unknown): NormalizedDiscoveredPosting[] {
      const parsed = careerPagePayloadSchema.safeParse(payload);
      if (!parsed.success) return [];
      return parsed.data.postings.map((p) =>
        normalizeCareerPagePosting(p, opts.defaultCompany)
      );
    }
  };
}

function normalizeCareerPagePosting(
  posting: z.infer<typeof careerPagePostingSchema>,
  defaultCompany: string | undefined
): NormalizedDiscoveredPosting {
  const company =
    posting.company?.trim() ||
    defaultCompany ||
    deriveCompanyFromUrl(posting.url);

  const locations = coerceLocations(posting.locations ?? null);
  const hasRemote = locations.some((l) => /remote/i.test(l));
  const onsiteLocations = hasRemote
    ? locations.filter((l) => !/remote/i.test(l))
    : locations;
  const isOnsiteRequired =
    locations.length === 0 ? null : hasRemote ? false : true;

  const description = posting.description ? htmlToText(posting.description) : null;

  return {
    source: "career_page",
    external_ref: null,
    url: posting.url,
    title: posting.title,
    company,
    description_excerpt: description,
    onsite_locations: onsiteLocations,
    is_onsite_required: isOnsiteRequired,
    employment_type: mapEmploymentTypeHint(posting.employment_type_hint ?? null),
    inferred_seniority_signals: inferSeniorityFromTitle(posting.title),
    raw_metadata: { ...posting }
  };
}

function coerceLocations(
  loc: string | string[] | null | undefined
): string[] {
  if (!loc) return [];
  if (typeof loc === "string") {
    const trimmed = loc.trim();
    return trimmed.length > 0 ? [trimmed] : [];
  }
  return loc.filter((s) => typeof s === "string" && s.trim().length > 0);
}

function mapEmploymentTypeHint(
  hint: string | null
): NormalizedDiscoveredPosting["employment_type"] {
  if (!hint) return null;
  const lower = hint.toLowerCase();
  if (/internship|intern/.test(lower)) return "internship";
  if (/contract[\s-]?to[\s-]?hire/.test(lower)) return "contract_to_hire";
  if (/contract/.test(lower)) return "contract";
  if (/full[\s-]?time/.test(lower)) return "full_time";
  return null;
}

/**
 * Derive a company name from the URL host. Strips common subdomains
 * ("careers", "jobs", "www") and the TLD, then capitalizes the first
 * letter. Best-effort — when this fails, returns "Unknown".
 *
 * Examples:
 *   https://anthropic.com/careers/...      → "Anthropic"
 *   https://careers.openai.com/...         → "Openai"
 *   https://jobs.netflix.com/positions/... → "Netflix"
 */
function deriveCompanyFromUrl(url: string): string {
  let host: string;
  try {
    host = new URL(url).hostname.toLowerCase();
  } catch {
    return "Unknown";
  }
  const stripped = host
    .replace(/^www\./, "")
    .replace(/^careers\./, "")
    .replace(/^jobs\./, "");
  const parts = stripped.split(".");
  if (parts.length === 0 || !parts[0]) return "Unknown";
  const root = parts[0];
  return root.charAt(0).toUpperCase() + root.slice(1);
}
